### ISSUE TITLE
How to help ?

### ISSUE THREAD

**Issue by ahumblenerd** [martin-raven/KeralaRescueApp#1]
Hello, 

I am Arun Purushothaman, from Google Developers Group. Do you require any help with the application ? We could reach out to fellow contributors.

- Arun Purushothaman

**Comment by martin-raven** [comment]
we are currently working on the xml . you can help by working on java. Designs are available in kerala rescue group.

**Comment by ahumblenerd** [comment]
Can you add the discussions group link ?

**Comment by martin-raven** [comment]
email me your number at : martinsiby@gmail.com
